/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.3.4
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as com_test_shared from "./../shared";
export import ICommonStruct = com_test_shared.ISharedStruct;
export import ICommonStructArgs = com_test_shared.ISharedStructArgs;
export import CommonStruct = com_test_shared.SharedStruct;
export import CommonStructCodec = com_test_shared.SharedStructCodec;
export import CommonUnionType = com_test_shared.SharedUnionType;
export import CommonUnion = com_test_shared.SharedUnion;
export import ICommonUnionWithOption1 = com_test_shared.ISharedUnionWithOption1;
export import ICommonUnionWithOption2 = com_test_shared.ISharedUnionWithOption2;
export import CommonUnionArgs = com_test_shared.SharedUnionArgs;
export import ICommonUnionWithOption1Args = com_test_shared.ISharedUnionWithOption1Args;
export import ICommonUnionWithOption2Args = com_test_shared.ISharedUnionWithOption2Args;
export import CommonUnionCodec = com_test_shared.SharedUnionCodec;
export import COMMON_INT = com_test_shared.SHARED_INT;
